user = User.create!(email: "aaaa@aaa.com",
                    password: "aaaaaa",
                    password_confirmation: "aaaaaa")

category_1 = user.categories.create!(name: "主専攻", credits: 48)
category_1_1 = category_1.children.create!(name: "学部科目の講義", credits: 24, user_id: user.id)
category_1_2 = category_1.children.create!(name: "基礎演習、基礎ゼミ", credits: 4, user_id: user.id)
category_1_3 = category_1.children.create!(name: "演習", credits: 4, user_id: user.id)
category_1_4 = category_1.children.create!(name: "残り", credits: 16, user_id: user.id)
category_2 = user.categories.create!(name: "副専攻", credits: 20)
category_3 = user.categories.create!(name: "外国語", credits: 24)
category_4 = user.categories.create!(name: "自由科目", credits: 32)
category_5 = user.categories.create!(name: "入門科目", credits: 4)

course1 = user.courses.create!(name: "授業1", credits: 2, category_id: category_1_1.id)
course2 = user.courses.create!(name: "授業2", credits: 2, category_id: category_1_1.id)
course3 = user.courses.create!(name: "授業3", credits: 3, category_id: category_1_1.id)
course4 = user.courses.create!(name: "授業4", credits: 2, category_id: category_1_1.id)
course5 = user.courses.create!(name: "授業5", credits: 2, category_id: category_1_2.id)
course6 = user.courses.create!(name: "授業6", credits: 2, category_id: category_1_3.id)
course7 = user.courses.create!(name: "授業7", credits: 2, category_id: category_1_3.id)
course8 = user.courses.create!(name: "授業8", credits: 2, category_id: category_1_4.id)
course9 = user.courses.create!(name: "授業9", credits: 4, category_id: category_1_4.id)
course10 = user.courses.create!(name: "授業10", credits: 3, category_id: category_2.id)
course11 = user.courses.create!(name: "授業11", credits: 3, category_id: category_2.id)
course12 = user.courses.create!(name: "授業12", credits: 2, category_id: category_2.id)
course13 = user.courses.create!(name: "授業13", credits: 2, category_id: category_3.id)
course14 = user.courses.create!(name: "授業14", credits: 2, category_id: category_3.id)
course15 = user.courses.create!(name: "授業15", credits: 2, category_id: category_3.id)
course16 = user.courses.create!(name: "授業16", credits: 2, category_id: category_4.id)